services:
  - type: web
    name: ironlink-crm
    env: node
    region: oregon
    plan: starter
    autoDeploy: true

    buildCommand: npm install
    startCommand: node server.js

    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: supersecureironlinktoken
